littledog:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Effort Controllers ---------------------------------------
  flhr_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_hip_roll
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  flhp_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_hip_pitch
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  flk_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_knee
    pid: {p: 100.0, i: 0.0, d: 0.5}


  frhr_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_hip_roll
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  frhp_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_hip_pitch
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  frk_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_knee
    pid: {p: 100.0, i: 0.0, d: 0.5}

  blhr_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_hip_roll
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  blhp_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_hip_pitch
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  blk_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_left_knee
    pid: {p: 100.0, i: 0.0, d: 0.5}

  brhr_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_hip_roll
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  brhp_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_hip_pitch
    pid: {p: 100.0, i: 0.0, d: 0.5}
    #pid: {p: 50.0, i: 0.1, d: 0.0}
  brk_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: back_right_knee
    pid: {p: 100.0, i: 0.0, d: 0.5}